### ISSUE TITLE
Next.js window is not defined

### ISSUE THREAD

**Issue by yvvw** [fewcha-wallet/aptos-web3#7]
![image](https://user-images.githubusercontent.com/15168529/184057609-5abcf954-a6b8-4818-b3d2-2862aa5f19f5.png)

Next.js run failed. due web3-react module can't be used in ssr mode.

**Comment by pierreneter** [comment]
@yvvw, let me check and reply to you as soon as possible

**Comment by pierreneter** [comment]
Fixed by https://github.com/fewcha-wallet/aptos-web3/pull/8 thanks @yvvw
